export const productsData = [
  {
    id: 1,
    name: "Laptop",
    price: 1500,
    description: "A high-performance laptop for all your needs.",
  },
  {
    id: 2,
    name: "Smartphone",
    price: 700,
    description: "A modern smartphone with an excellent camera.",
  },
  {
    id: 3,
    name: "Headphones",
    price: 200,
    description: "Noise-cancelling headphones for better focus.",
  },
  {
    id: 4,
    name: "Smartwatch",
    price: 300,
    description: "A stylish smartwatch with fitness tracking features.",
  },
  {
    id: 5,
    name: "Tablet",
    price: 600,
    description: "A powerful tablet for work and entertainment.",
  },
  {
    id: 6,
    name: "Wireless Mouse",
    price: 50,
    description: "A smooth and ergonomic wireless mouse for productivity.",
  },
  {
    id: 7,
    name: "Mechanical Keyboard",
    price: 120,
    description: "A durable mechanical keyboard with RGB lighting.",
  },
  {
    id: 8,
    name: "Gaming Monitor",
    price: 400,
    description: "A high-refresh-rate monitor for smooth gaming.",
  },
  {
    id: 9,
    name: "External Hard Drive",
    price: 100,
    description: "A 2TB external hard drive for extra storage.",
  },
  {
    id: 10,
    name: "Webcam",
    price: 80,
    description: "A full HD webcam for video calls and streaming.",
  },
  {
    id: 11,
    name: "Portable Charger",
    price: 60,
    description: "A high-capacity power bank for your devices.",
  },
  {
    id: 12,
    name: "Bluetooth Speaker",
    price: 150,
    description: "A compact and powerful speaker with deep bass.",
  },
  {
    id: 13,
    name: "VR Headset",
    price: 500,
    description: "A next-gen VR headset for immersive experiences.",
  },
  {
    id: 14,
    name: "Graphic Tablet",
    price: 250,
    description: "A professional drawing tablet for digital artists.",
  },
  {
    id: 15,
    name: "USB Hub",
    price: 40,
    description: "A multi-port USB hub for extra connectivity.",
  },
  {
    id: 16,
    name: "Gaming Chair",
    price: 300,
    description: "An ergonomic gaming chair with lumbar support.",
  },
  {
    id: 17,
    name: "Wireless Earbuds",
    price: 180,
    description: "High-quality wireless earbuds with noise cancellation.",
  },
  {
    id: 18,
    name: "Smart Home Assistant",
    price: 130,
    description: "A voice-controlled smart assistant for your home.",
  },
];
